server:
  port: 8900

--- #################### 数据库相关配置 ####################
spring:
  # 数据源配置项
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 排除 Druid 的自动配置，使用 dynamic-datasource-spring-boot-starter 配置多数据源
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration # 排除积木报表带来的 MongoDB 的自动配置
  datasource:
    druid: # Druid 【监控】相关的全局配置
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
        allow: # 设置白名单，不填则允许所有访问
        url-pattern: /druid/*
        login-username: mazongjian
        login-password: zxca123123x-+
      filter:
        stat:
          enabled: true
          log-slow-sql: true # 慢 SQL 记录
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic: # 多数据源配置
      druid: # Druid 【连接池】相关的全局配置
        initial-size: 5 # 初始连接数
        min-idle: 10 # 最小连接池数量
        max-active: 20 # 最大连接池数量
        max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
        time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
        min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
        max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
        validation-query: SELECT 1 FROM DUAL # 配置检测连接是否有效
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
      primary: master
      datasource:
        #修改为自己创建的mysql信息 支持5.7或8.0
        master:
          url: jdbc:mysql://182.44.14.243:8306/malaoban?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&connectTimeout=30000&socketTimeout=60000 # MySQL Connector/J 8.X 连接的示例
          username: malaoban
          password: FR7n6tW5xbzHmS3r

  # Redis 配置
  redis:
    host: 182.44.14.243 # 地址
    port: 8379 # 端口
    database: 15
    # 数据库索引
    password: redis_YM8kZT # 密码，建议生产环境开启

# 微信支付回调
wx:
  pay:
    #支付回调通知地址
    returnUrl: https://wq.scyanzu.com/app-api/callback/wxpay/update
    ################################以下内容为微信支付服务商模式以及分账配置############################################
    appId: wx9727cb1c69b545a7 #微信支付服务商的小程序APPID
    mchId: 1660250968 #微信支付服务商的商户号  如果不是服务商模式，这里就不填
    mchKey: 25f3ab3858f654cacd7d3737a9a97e80 #微信支付服务商的v2密钥    如果不是服务商模式，这里就不填
    # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
    keyPath: classpath:apiclient_cert.p12 # 如果不是服务商模式，这里就不填
    #开启分账功能 则需要填写接收分账的账户信息
    splitMchId: 1680122395 #接收分账的账户id
    splitMchName: 海口龙华区志轩盈网络科技工作室（个体工商户） #接收分账的账户名称  营业执照上的全称

#美团北极星平台开发者配置
meituan:
  redirectUrl: xxx
  appKey: xxxxxxxxxxxx
  secret: xxxxxxxxxxxx

#抖音开放平台开发者配置
douyin:
  redirectUrl: xxx
  appKey: xxxxxxxxxxxx
  secret: xxxxxxxxxxxx

#硬件开发者配置
iot:
  clientId: 5d3cf1ed-d534
  secret: 5942a5b9-292b-4be5-b00e-59f4f636dc4a
  redirectUrl: https://wq.scyanzu.com/app-api/callback/iotCallback
  groupPay: true #是否启用统一团购功能

